<a href="https://colab.research.google.com/github/dharvi120/numpy-100/blob/master/Copy_of_100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
import numpy as np
print(np.__version__)
np.show_config()



2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
import numpy as np
array=np.array([1,2,3,4,5])
print(array.nbytes)

40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
import numpy as np
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np
array=np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
import numpy as np
vector=np.arange(10)
sorted_vector=vector[::-1]
print(sorted_vector)

[0 1 2 3 4 5 6 7 8 9]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix=np.arange(9)
matrix.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array=([1,2,0,0,4,0])
np.nonzero(array)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
array=np.random.rand(3,3,3)
print(array)

[[[0.13314281 0.43309583 0.73642103]
  [0.99879993 0.82472369 0.83531686]
  [0.4703369  0.74656373 0.65454463]]

 [[0.70746397 0.35922732 0.2315124 ]
  [0.33632407 0.37351115 0.49952836]
  [0.80995972 0.69008935 0.36852873]]

 [[0.86017268 0.28501265 0.92464746]
  [0.41963283 0.34108048 0.1900916 ]
  [0.30436978 0.79055179 0.53379822]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
array=np.random.rand(10,10)
print(array)
print('maximum value:',np.max(array))
print('minimum value:',np.min(array))

[[0.39031346 0.18176148 0.43717973 0.91066134 0.43982544 0.07679665
  0.36034209 0.98540337 0.77825338 0.94581104]
 [0.03016924 0.96959778 0.00863489 0.57236463 0.99231549 0.64806745
  0.49277321 0.5824721  0.77782125 0.91681002]
 [0.70753182 0.81996344 0.03739883 0.95933485 0.54335864 0.13695871
  0.64034428 0.56416978 0.96321041 0.66797489]
 [0.18503973 0.24100781 0.71281027 0.60169877 0.2458622  0.45672312
  0.49801621 0.17936236 0.92150417 0.00938824]
 [0.40480514 0.77697814 0.95458347 0.65673746 0.76540057 0.85734516
  0.66760143 0.06100852 0.16395612 0.20122888]
 [0.85575443 0.60089617 0.09939684 0.75294989 0.45848422 0.58089145
  0.3525659  0.48272007 0.40307908 0.27540904]
 [0.84247862 0.09799173 0.63935893 0.05363131 0.76144411 0.48570507
  0.02662626 0.44790336 0.84091193 0.36694906]
 [0.4008385  0.59744177 0.43829083 0.63295267 0.80498859 0.28241394
  0.48488207 0.51304236 0.39493705 0.69694497]
 [0.76858281 0.85879153 0.37800335 0.41170834 0.32355184 0.24077859
  0.42739837

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
ran_vector=np.arange(30)
print(ran_vector)
print('mean value:',np.mean(ran_vector))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
mean value: 14.5


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np

import numpy as np

# inner zeros (3x3), border of 1's added
array = np.pad(np.zeros((3,3), dtype=int), pad_width=1, mode='constant', constant_values=1)
print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
array=np.ones((4,4))
array=np.pad(array,pad_width=1,mode='constant',constant_values=0)
print(array)


[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
false
false
nan
true
false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
import numpy as np
matrix=np.zeros((5,5),dtype=int)
matrix=np.diag([1,2,3,4],k=-1)

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
import numpy as np
matrix=np.zeros((8,8),dtype=int)
matrix[1::2,::2]=1
matrix[::2,1::2]=1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
array=np.arange(336).reshape(6,7,8)
print(array)
print(np.unravel_index(99,(6,7,8)))

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
matrix=np.array([[0,1],[1,0]])
matrix=np.tile(matrix,(4,4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix=np.random.rand(5,5)
matrix=(matrix-np.mean(matrix))/np.std(matrix)
print(matrix)

[[ 0.13903814  0.56574227  0.58151941 -1.92724121  0.24822454]
 [ 0.33231466 -0.84237202  1.09077819 -1.09005089 -0.99481837]
 [ 1.07735216 -0.92091129 -0.60330924  1.21534422 -0.30832914]
 [ 0.24228537  1.37294219  1.30274202 -1.13113508  0.55959402]
 [ 1.33677565 -0.99870236  1.08309002 -1.66873986 -0.66213339]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
unsigned_bytes=np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
print(unsigned_bytes)

[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1=np.arange(15).reshape(5,3)
matrix2=np.arange(6).reshape(3,2)
print(matrix1@matrix2)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np
array=np.arange(10)
array[(array>3)&(array<8)]*=-1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

0
1
2
3
4
9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
legal
legal
legal
legal
legal
illegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan (with RuntimeWarning)
	ZeroDivisionError
array([-9.22337204e+18]) (with warning)

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
import numpy as np

arr = np.array([1.2, -1.2, 3.7, -3.7, 0.0])
rounded = np.ceil(np.abs(arr)) * np.sign(arr)
print(rounded)


[ 2. -2.  4. -4.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,7])
print(np.intersect1d(arr,arr2))

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np
print(np.sqrt(-1) == np.emath.sqrt(-1))
##false

False


/tmp/ipython-input-3053658764.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
import numpy as np
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(yesterday)
print(today)
print(tomorrow)

2025-08-16
2025-08-17
2025-08-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np
dates_july=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(dates_july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np
A=np.array([1,2,3])
B=np.array([4,5,6])
np.add(A,B,out=B)
# np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[ -5 -14 -27]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
import numpy as np
arr=np.random.rand(4)*10
print(arr)
print(arr-arr%1)
print(np.floor(arr))
print(np.ceil(arr)-1)
print(arr.astype(int))
print(arr.astype(int))
print(arr//1)

[5.00298003 7.21124871 2.69975408 6.76432129]
[5. 7. 2. 6.]
[5. 7. 2. 6.]
[5. 7. 2. 6.]
[5 7 2 6]
[5 7 2 6]
[5. 7. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix=np.zeros((5,5))
matrix+=np.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
generator=(i for i in range(10))
array=np.fromiter(generator,dtype=int)
print(array)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
import numpy as np
vector=np.linspace(0,1,12,endpoint=True)[1:-1]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
arr=np.random.rand(10)
arr.sort()
print(arr)

[0.40251976 0.40275754 0.48047748 0.51222725 0.55186799 0.70156008
 0.70646916 0.78653258 0.85103584 0.98805924]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
np.add.reduce(arr)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
print(np.array_equal(arr1,arr2))

True


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr=np.array([1,2,3])
arr.flags.writeable=False
arr[0]=4

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
arr=np.random.rand(10,2)
print(arr)
x,y=arr[:,0],arr[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[[0.3087925  0.79804392]
 [0.65194363 0.1833542 ]
 [0.07359074 0.22326773]
 [0.34318329 0.74629952]
 [0.16694566 0.9777294 ]
 [0.3694745  0.27651875]
 [0.28102296 0.58713894]
 [0.82904599 0.93135829]
 [0.07999987 0.7331049 ]
 [0.05154342 0.70682419]]
[0.85570258 0.67723649 0.23508313 0.82142422 0.99187985 0.46149109
 0.65092706 1.24689435 0.73745696 0.70870103]
[1.20160186 0.27416042 1.25240266 1.13978421 1.40167895 0.64248333
 1.1243895  0.8434515  1.4621017  1.49800263]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [6]:
import numpy as np
vector=np.random.rand(10)
print(vector)
vector_max=np.max(vector)
vector[vector==vector_max]=0
print(vector)

[0.98479914 0.82695599 0.720148   0.82410697 0.36375989 0.2807897
 0.34841141 0.9144216  0.94618354 0.29287063]
[0.         0.82695599 0.720148   0.82410697 0.36375989 0.2807897
 0.34841141 0.9144216  0.94618354 0.29287063]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
arr=np.zeros((5,5),[('x',float),('y',float)])
arr['x'],arr['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(arr)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [9]:
import numpy as np
arrX=np.array([1,2,3])
arrY=np.array([4,5,6])
cauchy_matrix=1/np.subtract.outer(arrX,arrY)
print(cauchy_matrix)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [11]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [12]:
arr=np.random.rand(10)
np.set_printoptions(threshold=float('inf'))
print(arr)

[0.11317587 0.13487677 0.37120326 0.24203258 0.79085639 0.50916122
 0.8461239  0.79551629 0.75823094 0.7857065 ]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [13]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

66


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [14]:
arr=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(arr)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [15]:
arr=np.random.rand(100,2)
print(arr)
X,Y=np.atleast_2d(arr[:,0],arr[:,1])
D=np.sqrt((X-X.T)**2+(Y-Y.T)**2)
print(D)

[[0.47569675 0.52983554]
 [0.31348172 0.49148921]
 [0.34241307 0.99030311]
 [0.434343   0.16378308]
 [0.78993078 0.09548819]
 [0.19740272 0.82193729]
 [0.35503222 0.63274315]
 [0.681837   0.15724596]
 [0.22592113 0.06017888]
 [0.18404755 0.08602801]
 [0.873206   0.79761307]
 [0.19947376 0.73366062]
 [0.65072494 0.67401474]
 [0.83356911 0.1070748 ]
 [0.14003532 0.4859881 ]
 [0.47664615 0.53998644]
 [0.65424216 0.44049041]
 [0.89635358 0.42450384]
 [0.13544783 0.5713917 ]
 [0.68132304 0.83333701]
 [0.49847838 0.32583107]
 [0.51457987 0.9397256 ]
 [0.72949888 0.61902044]
 [0.84998669 0.96782183]
 [0.85669959 0.71330381]
 [0.43335609 0.85210189]
 [0.99839323 0.53502677]
 [0.19706382 0.12123475]
 [0.62212485 0.30931586]
 [0.85880362 0.21133306]
 [0.94749256 0.93761097]
 [0.58032586 0.47272853]
 [0.43615629 0.68421897]
 [0.70782716 0.21734791]
 [0.55055825 0.11915066]
 [0.65433724 0.3795178 ]
 [0.74430514 0.58007881]
 [0.9189939  0.59752325]
 [0.79232464 0.32711771]
 [0.35112766 0.42323347]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [16]:
arr=np.arange(10,dtype=np.float32)
arr=arr.astype(np.int32,copy=False)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
file_data=np.genfromtxt('file.txt',delimiter=',',dtype=np.int32)
print(file_data)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [17]:
arr=np.array([1,2,3])
for index,value in np.ndenumerate(arr):
    print(index,value)
for index in np.ndindex(arr.shape):
    print(index,arr[index])

(0,) 1
(1,) 2
(2,) 3
(0,) 1
(1,) 2
(2,) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

[[8.30757302e-01 4.51096051e-01 1.66621956e-01 3.65467241e-01
  4.49037123e-01]
 [5.73739014e-01 4.81329860e-04 8.46314122e-01 9.86123428e-01
  1.96084157e-01]
 [9.30129623e-01 6.68158256e-01 8.93817431e-01 2.68524590e-01
  5.92823448e-01]
 [4.48145754e-01 7.41664780e-01 1.82935662e-01 6.23793586e-01
  2.63002848e-01]
 [1.19437588e-01 6.72622929e-01 5.80132701e-01 6.42810518e-01
  3.51032445e-01]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [18]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [19]:
matrix=np.random.randn(3,3)
print(matrix)
print(matrix-matrix.mean(axis=1,keepdims=True))

[[ 0.44337631 -1.5604525   0.85272032]
 [ 0.52921467  1.84147109  0.19601813]
 [-0.4113751   0.92172929 -0.54267774]]
[[ 0.53149493 -1.47233388  0.94083894]
 [-0.32635329  0.98590313 -0.65954983]
 [-0.40060058  0.93250381 -0.53190322]]


#### 59. How to sort an array by the nth column? (★★☆)

In [20]:
arr=np.random.randint(0,10,(3,3))
arr_sort=arr.argsort(axis=0)
print(arr[arr_sort])

[[[4 6 2]
  [4 4 2]
  [4 6 2]]

 [[4 4 2]
  [4 6 2]
  [4 4 2]]

 [[6 6 8]
  [6 6 8]
  [6 6 8]]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [24]:
import numpy as np
arr=np.random.randint(0,3,(3,10))
print(arr)
print((~arr.any(axis=0)).any())

[[0 2 0 0 0 0 0 2 2 2]
 [0 2 0 2 1 0 2 1 1 2]
 [0 2 1 0 2 0 0 1 0 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [3]:
import numpy as np
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5460647716166307


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [5]:
arr1=np.arange(3).reshape(1,3)
arr2=np.arange(3).reshape(3,1)
print(arr1)
print(arr2)
it=np.nditer([arr1,arr2,None])
for x,y,z in it:
    z[...]=x+y
print(it.operands[2])

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [6]:
import numpy as np
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [13]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z, I, 1)
print(Z)

[2. 4. 3. 2. 3. 2. 5. 3. 4. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [18]:
import numpy as np
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [20]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
import numpy as np
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [21]:
import numpy as np

D = np.array([10, 20, 30, 40, 50])
S = np.array([1, 2, 1, 2, 1])  # subset labels (integers)

# Unique labels
labels, inverse = np.unique(S, return_inverse=True)

# Compute sum and count per subset
subset_sum = np.bincount(inverse, weights=D)
subset_count = np.bincount(inverse)

# Mean per subset
subset_mean = subset_sum / subset_count

print(dict(zip(labels, subset_mean)))



{np.int64(1): np.float64(30.0), np.int64(2): np.float64(30.0)}


#### 69. How to get the diagonal of a dot product? (★★★)

In [24]:
arr1=np.arange(9).reshape(3,3)
arr1=np.arange(9).reshape(3,3)
print(np.diag(np.dot(arr1,arr2)))

[5]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [25]:
vector=np.array([1,2,3,4,5])
vector_1=np.zeros(len(vector)+(len(vector)-1)*3)
vector_1[::4]=vector
print(vector_1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [26]:
arr=np.random.rand(5,5,3)
arr2=np.random.rand(5,5)
print(arr,arr2[::,None])

[[[0.20468685 0.93716371 0.4724694 ]
  [0.05484833 0.88098578 0.13733391]
  [0.01974479 0.51489188 0.37991707]
  [0.13654931 0.51485568 0.13906501]
  [0.31207448 0.32212368 0.29083586]]

 [[0.91948661 0.62672987 0.7058055 ]
  [0.14577295 0.32073608 0.46695584]
  [0.72625151 0.1023812  0.29784791]
  [0.19259106 0.47298357 0.05105109]
  [0.05164772 0.59200287 0.53314675]]

 [[0.9777426  0.57125572 0.99107052]
  [0.07205004 0.16328604 0.60352759]
  [0.26215067 0.63907696 0.5754528 ]
  [0.60750737 0.77953806 0.02647815]
  [0.68218913 0.2491321  0.61101067]]

 [[0.27704628 0.77853342 0.06222471]
  [0.35843522 0.69010327 0.28121505]
  [0.1702188  0.72799637 0.74779283]
  [0.46188339 0.89406955 0.25760454]
  [0.66610047 0.39096892 0.65321346]]

 [[0.45959608 0.54722414 0.54165902]
  [0.68082101 0.7021022  0.03030819]
  [0.26365568 0.59225185 0.7151865 ]
  [0.95362239 0.06374855 0.78957739]
  [0.96367228 0.9850963  0.1048577 ]]] [[[0.02608379 0.56717939 0.97195899 0.01240393 0.24245026]]

 [[0

#### 72. How to swap two rows of an array? (★★★)

In [28]:
arr1=np.random.randn(3,3)
print(arr1)
arr1[[1,0]]=arr1[[0,1]]
print(arr1)

[[ 0.35869235  0.40881298  1.51809814]
 [ 1.75301189  0.33576483 -1.20185851]
 [ 1.29308078  1.08250539  0.61622316]]
[[ 1.75301189  0.33576483 -1.20185851]
 [ 0.35869235  0.40881298  1.51809814]
 [ 1.29308078  1.08250539  0.61622316]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
import numpy as np

# Generate 10 triangles randomly with vertex labels from 0 to 5
num_triangles = 10
num_vertices = 6  # vertex labels 0,1,...,5

# Random triangles (integer vertex labels)
triangles = np.random.randint(0, num_vertices, size=(num_triangles, 3))
print("Triangles:\n", triangles)

# Step 1: Extract all edges
edges = np.vstack([
    triangles[:, [0, 1]],
    triangles[:, [1, 2]],
    triangles[:, [2, 0]]
])

# Step 2: Make edges order-independent
edges = np.sort(edges, axis=1)

# Step 3: Get unique edges
unique_edges = np.unique(edges, axis=0)
print("\nUnique edges:\n", unique_edges)



#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [30]:
import numpy as np
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [31]:

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [32]:
z=np.arange(5)
print(z)
print(sliding_window_view(z,window_shape=3))

[0 1 2 3 4]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [33]:
import numpy as np

bool_arr = np.array([True, False, True])
float_arr = np.array([1.5, -2.0, 3.0])

bool_arr[:] = ~bool_arr  # or np.logical_not(bool_arr)

float_arr *= -1

print("Negated booleans:", bool_arr)
print("Flipped floats:", float_arr)


Negated booleans: [False  True False]
Flipped floats: [-1.5  2.  -3. ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [36]:
import numpy as np
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(p)

[[9.19068123 6.6688116 ]]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [40]:
import numpy as np
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([(P0,P1,p_i) for p_i in p]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (10, 3) + inhomogeneous part.

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [42]:
def extract_subarray(arr, center, shape, fill=0):
    arr = np.asarray(arr)
    h, w = shape
    pad_h, pad_w = h//2, w//2
    arr_padded = np.pad(arr, ((pad_h,pad_h),(pad_w,pad_w)), constant_values=fill)
    r, c = center
    r_new, c_new = r + pad_h, c + pad_w
    return arr_padded[r_new-pad_h:r_new+pad_h+1, c_new-pad_w:c_new+pad_w+1]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [2]:
import numpy as np
arrayZ=np.arange(1,15)
print(arrayZ)
arrayR=np.array([arrayZ[i:i+4] for i in range(len(arrayZ)-3)])
print(arrayR)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [4]:
import numpy as np
matrix=np.random.randn(3,3)
print(matrix)
rank=np.linalg.matrix_rank(matrix)
print(rank)


[[ 1.50587007e+00 -2.32817176e-01  1.84007931e-03]
 [-5.99936022e-01  3.88370179e-01  2.58317141e+00]
 [-2.70852212e-01 -8.13324318e-01 -1.02590032e+00]]
3


#### 83. How to find the most frequent value in an array?

In [7]:
import numpy as np
arr=np.array([1,2,2,2,2,2,2,2,3,3,3,35,55])
print(arr)
print(np.bincount(arr).argmax())

[ 1  2  2  2  2  2  2  2  3  3  3 35 55]
2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [8]:
import numpy as np
matrix=np.random.rand(10,10)
print(matrix)
blocks=np.lib.stride_tricks.sliding_window_view(matrix,(3,3))
print(blocks)

[[0.46653605 0.29237689 0.18153909 0.61255871 0.71850211 0.37192792
  0.40137534 0.26086267 0.84697646 0.65025534]
 [0.41966103 0.82948564 0.95065097 0.41575791 0.54635501 0.84209344
  0.22167398 0.05972032 0.70992927 0.55569402]
 [0.09309549 0.16097731 0.25457655 0.89789312 0.29584937 0.71721053
  0.93511043 0.91731204 0.42872099 0.33420933]
 [0.66190467 0.7167376  0.8544244  0.70348943 0.911666   0.74417532
  0.33015468 0.84226149 0.8046223  0.50905301]
 [0.90271318 0.4969139  0.56492075 0.59965362 0.9968798  0.63514491
  0.63766559 0.01227797 0.56016462 0.83358081]
 [0.15372954 0.54302836 0.56501312 0.25842685 0.58901896 0.00182435
  0.60240796 0.76305829 0.6079703  0.89985952]
 [0.6793079  0.27259302 0.53890536 0.60457781 0.98804877 0.4240632
  0.86334916 0.25488395 0.13984519 0.84474576]
 [0.84127867 0.59063187 0.7144304  0.94267919 0.43767307 0.31852872
  0.62632116 0.15781541 0.24167017 0.03180123]
 [0.43645337 0.58262932 0.61157077 0.05485716 0.43179862 0.00862547
  0.45492763 

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [9]:
import numpy as np
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [10]:
import numpy as np
p_matrix=np.random.rand(3,3)
p_vector=np.random.rand(3,1)
print(p_matrix)
print(p_vector)
print(np.dot(p_matrix,p_vector))


[[0.69029297 0.41442529 0.49806028]
 [0.97317091 0.85095012 0.7551872 ]
 [0.9445949  0.36248899 0.25856238]]
[[0.32064574]
 [0.51868772]
 [0.73465766]]
[[0.80220061]
 [1.30822455]
 [0.68085376]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
arr=np.randomrand(16,16)
print(arr)
block_sum=np.add.reduceat(np.add.reduceat(arr,np.arange(0,arr.shape[0],4),axis=0),np.arange(0,arr.shape[1],4),axis=1)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)
```

#### 89. How to get the n largest values of an array (★★★)

In [11]:
import numpy as np
arr=np.random.rand(10)
print(arr)
print(np.sort(arr)[-3:])

[0.75092201 0.6311908  0.35275309 0.34835384 0.61528611 0.5456255
 0.75121171 0.49754492 0.80830504 0.76372407]
[0.75121171 0.76372407 0.80830504]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [14]:
import numpy as np
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [15]:
vectorZ=np.random.rand(10)
print(vectorZ)
print(np.power(vectorZ,3))
print(vectorZ*vectorZ*vectorZ)

[0.81862437 0.92720965 0.22504553 0.4581074  0.85225368 0.26814627
 0.76231288 0.30009102 0.67349501 0.52032062]
[0.54859773 0.79713858 0.01139754 0.09613951 0.6190228  0.01928037
 0.44299597 0.02702458 0.30549433 0.14086824]
[0.54859773 0.79713858 0.01139754 0.09613951 0.6190228  0.01928037
 0.44299597 0.02702458 0.30549433 0.14086824]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [17]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
print(A)
print(B)
C=(A[...,np.newaxis,np.newaxis]==B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[[4 1 4]
 [4 4 4]
 [0 1 2]
 [1 2 2]
 [4 1 4]
 [0 2 4]
 [1 4 0]
 [1 2 3]]
[[1 4]
 [4 4]]
[0 1 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [18]:
matrix=np.random.rand(10,3)
print(matrix)
print(matrix[~np.all(matrix[:,1:]==matrix[:,:-1],axis=1)])

[[0.43462723 0.52987242 0.20016766]
 [0.80998066 0.10489114 0.61567526]
 [0.52735237 0.36164343 0.62504481]
 [0.4634079  0.02322749 0.98126517]
 [0.24688367 0.42533767 0.89272821]
 [0.35594485 0.51257858 0.23327783]
 [0.75828396 0.59266473 0.76844206]
 [0.72290554 0.55420319 0.64595388]
 [0.02544827 0.48069676 0.76764811]
 [0.68509291 0.76291341 0.94597755]]
[[0.43462723 0.52987242 0.20016766]
 [0.80998066 0.10489114 0.61567526]
 [0.52735237 0.36164343 0.62504481]
 [0.4634079  0.02322749 0.98126517]
 [0.24688367 0.42533767 0.89272821]
 [0.35594485 0.51257858 0.23327783]
 [0.75828396 0.59266473 0.76844206]
 [0.72290554 0.55420319 0.64595388]
 [0.02544827 0.48069676 0.76764811]
 [0.68509291 0.76291341 0.94597755]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [19]:
arr=np.random.randint(0,2,(6,3))
print(arr)
unique_rows=np.unique(arr,axis=0)
print(unique_rows)

[[0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 1 1]
 [0 0 1]]
[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [21]:
a=np.random.rand(10)
b=np.random.rand(10)
print(np.einsum('i->',a))
print(np.einsum('i,i->i',a,b))
print(np.einsum('i,i',a,b))
print(np.einsum('i,j',a,b))

6.487882777275253
[0.81489798 0.61544967 0.4877429  0.36821192 0.42355323 0.34529031
 0.42408277 0.19686124 0.18898993 0.02112501]
3.886204956333488
[[0.81489798 0.56078343 0.4497534  0.51552002 0.53107978 0.38466153
  0.5615513  0.36975463 0.90593295 0.29708294]
 [0.89433578 0.61544967 0.49359621 0.56577389 0.58285045 0.42215907
  0.61629239 0.40579902 0.99424501 0.32604315]
 [0.8837303  0.60815135 0.4877429  0.55906466 0.57593871 0.41715289
  0.60898408 0.40098685 0.98245475 0.32217677]
 [0.58204364 0.40054147 0.32123789 0.36821192 0.37932553 0.2747458
  0.40108992 0.2640985  0.64706568 0.2121925 ]
 [0.64990739 0.44724285 0.35869282 0.41114382 0.42355323 0.30677996
  0.44785526 0.29489123 0.72251071 0.23693322]
 [0.73149081 0.50338562 0.40371984 0.46275505 0.47672223 0.34529031
  0.5040749  0.33190918 0.81320809 0.26667564]
 [0.61540983 0.42350287 0.33965314 0.38932001 0.40107072 0.29049586
  0.42408277 0.27923819 0.68415931 0.22435663]
 [0.43386022 0.29856698 0.23945342 0.27446826 0

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [23]:
import numpy as np
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
data_2d = np.array([x, y]).T
print(data_2d)

[[ 0.00000000e+00  0.00000000e+00]
 [ 9.95004165e-02  9.98334166e-03]
 [ 1.96013316e-01  3.97338662e-02]
 [ 2.86600947e-01  8.86560620e-02]
 [ 3.68424398e-01  1.55767337e-01]
 [ 4.38791281e-01  2.39712769e-01]
 [ 4.95201369e-01  3.38785484e-01]
 [ 5.35389531e-01  4.50952381e-01]
 [ 5.57365367e-01  5.73884873e-01]
 [ 5.59448971e-01  7.04994219e-01]
 [ 5.40302306e-01  8.41470985e-01]
 [ 4.98955734e-01  9.80328096e-01]
 [ 4.34829305e-01  1.11844690e+00]
 [ 3.47748477e-01  1.25262564e+00]
 [ 2.37954000e-01  1.37962962e+00]
 [ 1.06105803e-01  1.49624248e+00]
 [-4.67192357e-02  1.59931776e+00]
 [-2.19035640e-01  1.68583018e+00]
 [-4.08963770e-01  1.75292574e+00]
 [-6.14250177e-01  1.79797017e+00]
 [-8.32293673e-01  1.81859485e+00]
 [-1.06017682e+00  1.81273967e+00]
 [-1.29470246e+00  1.77869209e+00]
 [-1.53243485e+00  1.71512199e+00]
 [-1.76974492e+00  1.62111163e+00]
 [-2.00285904e+00  1.49618036e+00]
 [-2.22791076e+00  1.34030357e+00]
 [-2.44099478e+00  1.15392568e+00]
 [-2.63822255e+00  9

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])
```

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)